### ISSUE TITLE
Can't install the extension to firefox - Corrupt addon

### ISSUE THREAD

**Issue by vassijoseph** [DannyAlas/DGG-Everywhere#12]
When trying to install the extension to firefox I get the message that it "appears to be corrupt"

To make a long story short, I found the problem, the zip file has the folder in which there are the files of the addon, the zip has to not have the folder, it needs to have the files straight up

I tried to temporarily install it locally and got a message that manifest version 3 isn't supported so I changed it to 2 and now it is installable, I don't know if the manifest thing is irrelevant but just saying

**Comment by DannyAlas** [comment]
It appears that this will require some version handling in the code. Will work on it for the next update.

For now, I will temporarily disable this. Instead you may install as [temporary add-on](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/) or through the [Add-on Store](https://addons.mozilla.org/en-US/firefox/addon/dgg-everywhere/)

**Comment by jeruhmyuh** [comment]
If you point me in the right direction for the version changes I'm willing to take a look
