### ISSUE TITLE
Still can't login to to destiny.gg when trying to use the extension on youtube

### ISSUE THREAD

**Issue by realroal** [DannyAlas/DGG-Everywhere#19]
When I type in the chat extension it asks me to login, and when I press the button the page goes white and it has an error saying "www.destiny.gg refuses to connect"

**Comment by DannyAlas** [comment]
In the works. (I'll most likely just override the login prompt if cookies aren't found)

**In the meantime**, just make sure you're logged into https://www.destiny.gg in the browser, and the login session will carry into the embed.

**Comment by realroal** [comment]
> In the works. (I'll most likely just override the login prompt if cookies aren't found)
> 
> **In the meantime**, just make sure you're logged into https://www.destiny.gg in the browser, and the login session will carry into the embed.

I am logged into dgg when I use this extension, it still doesn't work.

**Comment by DannyAlas** [comment]
Could you please post the following info:

- The browser you're using, and it's version
- The extension version
- What platform it is not working on

Also, please check that you have session cookies for destiny.gg while embedding the chat in Youtube, Kick, etc. It should look something like the image below, with the "rememberme" signifying the session cookie. **DO NOT POST THIS!** Just check that it is present. If you're unsure about how to do this, see here for [Chrome](https://developer.chrome.com/docs/devtools/application/cookies/), [Firefox](https://firefox-source-docs.mozilla.org/devtools-user/storage_inspector/index.html), [Edge](https://support.microsoft.com/en-us/microsoft-edge/view-cookies-in-microsoft-edge-a7d95376-f2cd-8e4a-25dc-1de753474879)

![Untitled](https://github.com/DannyAlas/DGG-Everywhere/assets/81212794/4e6b1b4a-e678-4b21-85a9-610edad999f6)

**Comment by realroal** [comment]
Google Chrome Version 114.0.5735.199
DGG Chat Everywhere 0.2.2
Doesn't work on Youtube or Kick
Yes rememberme is there.

**Comment by realroal** [comment]
Any update on this? @DannyAlas

**Comment by DannyAlas** [comment]
This doesn't appear to be an issue with extension, not reproducible.  Something else, such another extension, is possibly interfering. The authentication flow is handled by destiny.gg not me.
