### ISSUE TITLE
Can't sign in on firefox

### ISSUE THREAD

**Issue by OmegaOnion** [DannyAlas/DGG-Everywhere#23]
When you click log in to chat in firefox I get the following:

Firefox Can’t Open This Page

To protect your security, www.destiny.gg will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.

Learn more…

Report errors like this to help Mozilla identify and block malicious sites

**Comment by excludes** [comment]
disable this and it will work :)

![](https://i.imgur.com/0T3SyXv.png)
